### ISSUE TITLE
Solo buttons dont have solo functionality on RPCS3

### ISSUE THREAD

**Issue by oiledupscourgegyatt** [TheNathannator/RB4InstrumentMapper#12]
They just act as the normal frets

**Comment by TheNathannator** [comment]
I might have gotten the mapping for the solo fret flag wrong, will have to double-check that. Thanks for the report!

**Comment by TheNathannator** [comment]
Finally got around to looking at this; things are more complicated than I initially remembered them to be. The mapping is correct, RB guitars use the L2 press input for the solo fret flag. There's no direct analog for that on Xbox 360 controllers, so RB4InstrumentMapper sets the left trigger to max to simulate it.

If you can see the input being triggered in e.g. joy.cpl, it's a mapping issue on RPCS3's side, and there's nothing I can do to fix this if the default mappings don't work. Make sure you have the left trigger bound to L2 in RPCS3.

**Comment by TheNathannator** [comment]
Apologies for the delay, been busy.

"Doesn't work" is not very helpful for this. Can you check in joy.cpl to see if all the inputs are registering correctly? As I said above:
> If you can see the input being triggered in e.g. joy.cpl, it's a mapping issue on RPCS3's side, and there's nothing I can do to fix this if the default mappings don't work. Make sure you have the left trigger bound to L2 in RPCS3.

**Comment by cameron44251** [comment]
![image](https://github.com/user-attachments/assets/4e20d66c-9178-45d5-8b12-3ca7e03866de)
im on a riffmaster first image is me holding blue and second is the blue solo fret
![image](https://github.com/user-attachments/assets/9ba0d247-8326-495b-9a51-840b5075bc78)

**Comment by flash1228** [comment]
![rm solo green](https://github.com/user-attachments/assets/dc610aeb-fb4a-4ef4-a30d-5707e903a255)

**Comment by flash1228** [comment]
It looks like RB 360 guitars use LS for the activation flag for solo frets?

**Comment by cameron44251** [comment]
Latest commit seems to fix it

**Comment by TheNathannator** [comment]
Awesome, figured it would! Will get that into a new release soon, just refactoring some of my packet replay stuff so I can run through everything and double-check all the behavior is expected.

**Comment by TheNathannator** [comment]
Fix is now in a published release, [v5.0.4](https://github.com/TheNathannator/RB4InstrumentMapper/releases/tag/v5.0.4).
