### ISSUE TITLE
Activates for the riffmaster but the wammy controls the mouse cursor

### ISSUE THREAD

**Issue by flaystus** [TheNathannator/RB4InstrumentMapper#14]
Activates for the riffmaster (xbox version) but the wammy controls the mouse cursor which goes right to the far left of the screen. You can move the mouse by using tilt of the controller and the wammy sort of but its not usable.

**Comment by TheNathannator** [comment]
This is not a capability RB4InstrumentMapper has; if you're running Steam, make sure you have Steam Input disabled, as this is what its default desktop configuration does.

**Comment by flaystus** [comment]
Thank you! You are the king of humans!
