### ISSUE TITLE
XB1 Strat Whammy/Tilt issues

### ISSUE THREAD

**Issue by AltEvolutions** [TheNathannator/RB4InstrumentMapper#22]
I just updated to 5.0.0.0 and both the whammy and tilt no longer function automatically like they used to.

The packet logs pick up every other button press correctly, but both the tilt and whammy functions don't actually act like they're being "pressed" at all. By chance I did manage to deduce that both the 3rd (tilt) and 4th (whammy) numbers do actually change based on movement of each (if you press a button at the same time to trigger a packet) so they're clearly being picked up in some form. 

I did re-install 4.2.0.0 to see what that said in the debug logs with winpcap and sure enough that picked up both the tilt of the guitar and the pressing of the whammy bar as button presses

**Comment by TheNathannator** [comment]
Weird; I noticed that when I was testing with FestivalInstrumentMapper (due to lack of XB1 instruments to test with locally), but I thought it was just a weird issue with all the hoops that has to go through just to work lol. I'll have to take a closer look.

**Comment by charles-peter** [comment]
Just chiming in to say I see the same issue.
I also tried the calibrate fix from another thread and remapping; neither worked.

**Comment by TheNathannator** [comment]
I've figured out the problem, the timestamps given by GameInput aren't updated on guitar axis changes, only on button presses. I'll have a fix out sometime soon!

It *does* correctly update the timestamp for gamepad axis changes, which is why I didn't pay much attention to the issue initially. Definitely a bug on GameInput's end somewhere lol

**Comment by TheNathannator** [comment]
Should be fixed now in [v5.0.1](https://github.com/TheNathannator/RB4InstrumentMapper/releases/tag/v5.0.1), give it a go and lemme know! Closing for now since I was able to confirm on my end.

**Comment by AltEvolutions** [comment]
Can confirm, all works for me now!

**Comment by TheNathannator** [comment]
Awesome!
