### ISSUE TITLE
Whammy not working in RPCS3, Clone Hero tilt issues.

### ISSUE THREAD

**Issue by TacoRaptor67** [TheNathannator/RB4InstrumentMapper#23]
First off, love that this application exists :D it allows me to use my Xbox One Jaguar. Thanks! I was also having the tilt/whammy issue from before the latest update, and that only seems to have been fixed a little bit for me. Tilt now works in RPCS3 on RB3, but whammy does not (RPCS3 compatibility mode). On Clone Hero (v1.0.0.4080-final, regular ViGEmBus) tilt doesn't seem to work for activating Star Power, but _does_ work when mapping the controller. Whammy works just fine after calibrating (at first I was having the same issue as #21 where it sounded like the whammy was being held down).

**Comment by TheNathannator** [comment]
I'm not sure why whammy wouldn't be working in RPCS3 mode, unless it has to do with how I made it only use half of the range to prevent issues in the rebinding menu. Can you press Win + R, type in `joy.cpl`, and check if it responds there?

For tilt in CH, that *should* be working correctly as well, you just might need to tilt really far for it to activate (in the calibration view, the point at which the top arrow hits 1 is the point at which SP will activate). You normally would be able to adjust this by adjusting the Sensitivity slider in the axis calibration settings, but I just discovered that the deadzone and sensitivity settings [happen to be bugged](https://strikeline.myjetbrains.com/youtrack/issue/CH-849) on the axis that WiitarThing and RB4InstrumentMapper put tilt on lol

**Comment by TacoRaptor67** [comment]
Whammy seems to work fine in joy.cpl (X Rotation half-full by default, then fills to the right when pressed) but trying with RB3 Deluxe does nothing. I messed with calibration on CH and it shows the Y axis moving up to one and back as I fully tilt it, but no amount of tilting activates it.

**Comment by TheNathannator** [comment]
Asked around for the RPCS3 issue, it most likely is indeed due to the workaround I did for the rebinding menu. I removed it in [v5.0.2](https://github.com/TheNathannator/RB4InstrumentMapper/releases/tag/v5.0.2), give that a shot and see if it's fixed now.

Seeing as tilt responds in CH, I'm going to presume there's nothing wrong on RB4IM's side. Double-check that you have Tilt Axis bound to Right Stick Y, and also make sure you have the Tilt option enabled in your profile settings (I keep forgetting this is a thing lol).

**Comment by TacoRaptor67** [comment]
> Seeing as tilt responds in CH, I'm going to presume there's nothing wrong on RB4IM's side. Double-check that you have Tilt Axis bound to Right Stick Y, and also make sure you have the Tilt option enabled in your profile settings (I keep forgetting this is a thing lol).
>
-_- Welp... that's a thing I also completely forgot about, lol. CH issue fixed. RB3 Whammy also works now! Thank you.

**Comment by TheNathannator** [comment]
Heck yeah, you're welcome!
