### ISSUE TITLE
Failed to create GameInput instance: 0x80004001

### ISSUE THREAD

**Issue by MightyAries** [TheNathannator/RB4InstrumentMapper#27]
This is related to the Riffmaster for Fortnite Festival. I've tried to set it up on two PCs - on one it works flawlessly, even with Fortnite Festival.

Both systems are built using the same parts but on the second PC, neither Clone Hero nor Fortnite Festival recognize the Riffmaster. The only difference I've noticed is that on the PC where it doesn't work, RB4InstrumentMapper returns the error "**_Failed to create GameInput instance: 0x80004001_**"

![photo_2024-07-16_16-55-10](https://github.com/user-attachments/assets/c7842c04-659f-41ba-87a9-bf1b25387959)

I've tried to find a solution for this, but after hours, still made no progress. The only hint is the **GameInput Backend** doesn't even register the connected Riffmaster, which is probably why Fortnite Festival doesn't recognize it either. 

Even with nothing connected to the PC, simply booting up RB4InstrumentMapper returns the aforementioned error. 

Any help would be greatly appreciated. I even made sure that GameInputSvc and GamingServicesNet are running, in case they're related to this, but that also didn't fix this.

**Comment by TheNathannator** [comment]
> the GameInput Backend doesn't even register the connected Riffmaster

Because the GameInput backend isn't even initializing properly in the first place lol

Something is very wrong with the install of GameInput on this PC; `0x80004001` is `E_NOTIMPL` which means the function being called isn't implemented yet, but that 100% should not be the case for initialization.

Best I can suggest is to try reinstalling RB4InstrumentMapper, it bundles the redistributable installer for GameInput and runs it during installation. Perhaps that'll help fix things, but I can't say for certain since this issue is entirely out of RB4IM's control.

The last thing I'd be able to suggest is running the redistributable installer manually. Microsoft doesn't provide a direct download for it unfortunately, and GitHub doesn't let me upload it to here, so you'll have to [download the package manually](https://www.nuget.org/api/v2/package/Microsoft.GameInput/0.2303.22621.3038), extract it with a tool like [7-Zip](https://7-zip.org/) (right-click the downloaded .nupkg and hit 7-Zip > Open Archive), and go to the `redist` folder to get to it.

**Comment by MightyAries** [comment]
Thank you so much for that! I had already tried restalling RB4InstrumentMapper multiple times, but the linked redistributable installer pointed me in the right direction. 

I appreciate that you linked me where I could get the package, since that led me to find out that I can't even install, repair or uninstall GameInputRedist at all on that PC. When I try to install it, nothing happens after I start the installation attempt - and repair and uninstall just return an error stating that it needs to be installed first before those two actions can be taken. 

I guess now I'll have to find out how to fix that, but at least I got an angle I can pursue. Thank you so much!

**Comment by TheNathannator** [comment]
Do you not get any kind of window that pops up? It should show one for a split second, and then close; it doesn't guide you through anything (at least not in my experience, but I also already have it installed lol).

**Comment by MightyAries** [comment]
I only received the general pop-up of Windows unpacking and preparing to install it, followed by the admin pop-up if I want to allow the software to make changes (which I obviously confirm). 

Good call about the event viewer though! I tried installing it again just now so I would have the most recent log files and two entries showed it was successful without any errors.

![image_2024-07-17_11-57-03](https://github.com/user-attachments/assets/6f5cbc83-f581-458c-b14c-e473442429b4)
![image_2024-07-17_11-57-13](https://github.com/user-attachments/assets/a876ad38-1aa3-4132-9620-643875ded229)

I did try booting RB4InstrumentMapper again as well and then took a look at the logs. I'm not sure if this helps at all, but I really appreciate your thoughts.

![image_2024-07-17_12-02-55](https://github.com/user-attachments/assets/d822017a-3ca8-458f-a1ea-d2ccb65a135b)
![image_2024-07-17_12-02-552](https://github.com/user-attachments/assets/d2e0733f-8aa0-411e-944c-55edca9ad4a4)
![image_2024-07-17_12-02-553](https://github.com/user-attachments/assets/b5680345-a8fe-49e1-b148-5d3b6119978d)

So at this point I wonder if I just need to reinstall Windows? Fully remove Xbox and the Gaming Service to try reinstalling it again? I honestly am at a loss of ideas and searching online hasn't yielded any other angles to pursue either.

**Comment by TheNathannator** [comment]
Yeah, this is all very weird lol. A full reinstall might be the best course of action then, nothing else I can think of myself either.

**Comment by MightyAries** [comment]
I'll give a Windows reinstall a shot then. Thank you so much for your help!

**Comment by emongev** [comment]
I was having a very similar issue, although mine said "Failed to create GameInput instance: 0xD0000034".

-Did the RB4InstrumentMapper repair. No dice.
-Did the RB4InstrumentMapper uninstall/reinstall. No dice.
-Did the GameInput redist install. No dice.

Finally what I did to fix it was:

-Went into task manager.
-Typed "gameinput" on the search bar.
-Stopped the GameInputSvc by right clicking it.
-Started the GameInputSvc by right clicking it.
-RB4InstrumentMapper immediately started working again.

**Comment by MightyAries** [comment]
@emongev Sadly that one didn't work for me, though I'm glad it fixed your issue!

**Comment by MightyAries** [comment]
@TheNathannator Took a while because my husband didn't want to reinstall Windows / we didn't find the time to, buuuut we finally got around to and it works like a charm. 

Thank you so much for your help and advice, we wouldn't have thought of it without your input!

**Comment by TheNathannator** [comment]
Nice, glad you got it worked out finally!
