### ISSUE TITLE
Converting RiffMaster driver to WinUSB possibly flashing the dongle firmware

### ISSUE THREAD

**Issue by gamerbross** [TheNathannator/RB4InstrumentMapper#30]
My RiffMaster (Xbox) was working perfectly for one or two weeks. I played Clone Hero, YARG and FN Festival, and only used this 3rd party software. The main feature, emulating ViGEmBus controller, doesn't do anything bad, but (I don't remember when I used it) converting the controller to WinUSB seemed to flash the dongle firmware or something weird with it. Now my whammy bar goes from not pressed to fully pressed instantly (with the minimum detection goes to full). Also, the joystick analog movement doesn't work (the joystick click does work)

https://github.com/user-attachments/assets/9c89201a-f4d6-4aaa-b897-3f74f06d9d81

_YARG control binding, showing the whammy going from pressed to not pressed instantly_

`[33] -> 20 | 00-00-6A-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00`
`[33] -> 20 | 00-00-6A-FF-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00`
_RB4InstrumentMapper packets of the whammy bar, showing how a byte goes from `00` to `FF`_

https://github.com/user-attachments/assets/f626dc9e-1c6d-42bb-bed3-9e53c4ecdff3

_https://hardwaretester.com/gamepad with RB4InstrumentMapper on showing the whammy not working properly and "showing" how the joystick analog movement doesn't work but the click does_

---
[Here's a post](https://www.reddit.com/r/CloneHero/comments/1enbwh5/riffmaster_dongle_flashed/) in r/CloneHero Subreddit I made about this problem.

**Comment by TheNathannator** [comment]
There's no possible way for switching the driver to WinUSB to touch the device firmware, drivers are entirely on Windows' side of things. Not sure why it would suddenly be doing this, hm.

**Comment by gamerbross** [comment]
Update, this doesn't look related to the dongle, the wired function doesn't do anything, my PC shows a new device but doesn't receive anything. The pre-release v5.0.5 doesn't recognize anything at all, Steam Input also doesn't. Could it be a factory problem?

**Comment by gamerbross** [comment]
i talked to the pdp support and yea, it seems to be a factory problem. Im gonna change it for a new one
