### ISSUE TITLE
Riffmaster Wired Support

### ISSUE THREAD

**Issue by pellux-network** [TheNathannator/RB4InstrumentMapper#32]
After searching to see if I could use my PDP Riffmaster wired, I came across [this](https://www.reddit.com/r/FortniteFestival/comments/1cjcrdv/comment/lhr2ykw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) comment on Reddit which claimed plugging in the Riffmaster while holding all (or possibly some?) of the fret buttons brings up a wired USB connection to the controller. I tried this myself, and low and behold it showed up in my devices and in the "Configure USB Devices" menu of RB4InstrumentMapper

![Screenshot 2024-08-13 004057](https://github.com/user-attachments/assets/1b6d53dc-54f9-44d4-9317-127fc92c70b9)

However, as expected since no one thought the guitar could even be used wired, RB4InstrumentMapper doesn't have the proper mappings and refuses to do so, throwing these GUIDs:

![Screenshot 2024-08-13 003847](https://github.com/user-attachments/assets/0a304dc6-83f4-4c9f-a40a-2474ceec2145)

I'm not too sure how the tech works and I'm no programmer either, but this seems to imply the Riffmaster _can_ be used wired! Would it be possible to get the mapping in RB4InstrumentMapper?

**Comment by TheNathannator** [comment]
Interesting, nice find! I'll see what I can do. It looks like the product ID is different as well, `0247` instead of `0248`.

I'll make some changes to make it possible to log inputs from these devices and post a build. I'll need you to send a log for those inputs to see what exactly it sends, I don't want to assume it's the same and have problems arise from that.

**Comment by TheNathannator** [comment]
Published a pre-release here which should let you grab an input report log:
https://github.com/TheNathannator/RB4InstrumentMapper/releases/tag/v5.0.5-pre1

After you have it installed:
1. Disconnect the Riffmaster.
2. Enable the Show Packets and Log Packets to File options:
   ![image](https://github.com/user-attachments/assets/4f4b40b0-7c5a-4c51-90ef-6644f9c99626)
3. Hit Start, then connect the Riffmaster. Connecting it now will allow important connection info to get logged, in addition to the inputs.

**Comment by pellux-network** [comment]
> Published a pre-release here which should let you grab an input report log: https://github.com/TheNathannator/RB4InstrumentMapper/releases/tag/v5.0.5-pre1
> 
> After you have it installed:
> 
> 1. Disconnect the Riffmaster.
> 2. Enable the Show Packets and Log Packets to File options:
>    ![image](https://private-user-images.githubusercontent.com/29052821/357356046-4f4b40b0-7c5a-4c51-90ef-6644f9c99626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDUyNDksIm5iZiI6MTcyMzU0NDk0OSwicGF0aCI6Ii8yOTA1MjgyMS8zNTczNTYwNDYtNGY0YjQwYjAtN2M1YS00YzUxLTkwZWYtNjY0NGY5Yzk5NjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MTk2NjgwMGJiZWI1NTAxNmI3YjdmNDlmNjE5M2Q3ZDMxNzJjNzRjM2NhYTZkNWMxZDA2NzA2YTNkNDc5Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.snV-tRF2S2HdL70DUjdW-HJ5lQyiJkI5ICHDuMHoQW0)
> 3. Hit Start, then connect the Riffmaster. Connecting it now will allow important connection info to get logged, in addition to the inputs.

Thanks for the reply! Definitely willing to do whatever is needed to help get this working 😊. Hopefully, I did everything correctly, here's the log file as requested: [log_2024-08-13_06-32-38.txt](https://github.com/user-attachments/files/16598107/log_2024-08-13_06-32-38.txt)

**Comment by TheNathannator** [comment]
I guess I forgot to specify lol, did you press things on the Riffmaster after you plugged it in? I don't see any input reports in this log.

**Comment by pellux-network** [comment]
> I guess I forgot to specify lol, did you press things on the Riffmaster after you plugged it in? I don't see any input reports in this log. It does have the connection info though, at least.

Yeah I did press buttons, but they don't seem to do anything at all, unfortunately. Should I be using the GameInput drivers or the WinUSB drivers? I've been using WinUSB. Also this is appears, in the console:

```
[2024-08-13 06:25:39.052] [05] <- 05-20-00-01 | 07
**Error while reading packet! (Attempt 1)
Nefarius.Drivers.WinUSB.USBException: Failed to read from pipe. ---> Nefarius.Drivers.WinUSB.API.APIException: Failed to read pipe on WinUSB device. ---> System.ComponentModel.Win32Exception: The I/O operation has been aborted because of either a thread exit or an application request
```

Is that an issue?

Here's the entire console output, in case that helps you any:

```
No vJoy driver found, or vJoy is disabled. vJoy selection will be unavailable.
ViGEmBus found!
Created main log file.
USB device \\?\usb#vid_0e6f&pid_0247#0000db87a72a2019#{a5dcbf10-6530-11d2-901f-00c04fb951ed} connected
GameInput device 12-98-7C-EF-0A-47-B8-F3-8C-FB-39-2F-6D-61-55-3D-C9-9A-EB-F0-8E-14-C3-0D-70-94-51-87-2F-BF-FD-03 connected
USB device \\?\usb#vid_0e6f&pid_0247#0000db87a72a2019#{a5dcbf10-6530-11d2-901f-00c04fb951ed} disconnected
Created packet log file.
Device with hardware IDs 0E6F:0247 is not recognized! Device will not be mapped.
USB device \\?\usb#vid_0e6f&pid_0247#0000db87a72a2019#{a5dcbf10-6530-11d2-901f-00c04fb951ed} connected
[2024-08-13 06:25:21.370] [32] -> 02-20-01-1C | 19-20-2A-A7-87-DB-00-00-6F-0E-47-02-01-00-00-00-00-00-10-00-01-00-01-00-01-00-01-00
New client connected with ID DB87A72A2019
[2024-08-13 06:25:21.372] [04] <- 04-20-01-00 | 
[2024-08-13 06:25:21.377] [64] -> 04-F0-02-3A-D6-02 | 10-00-01-00-00-00-00-00-00-00-00-00-00-00-56-01-A4-00-16-00-1B-00-1C-00-23-00-29-00-73-00-00-00-00-00-00-00-00-00-01-01-00-00-00-00-06-01-02-03-04-06-07-05-01-04-05-06-0A-02
[2024-08-13 06:25:21.377] [13] <- 01-20-02-09 | 00-04-20-3A-00-00-00-1C-01
[2024-08-13 06:25:21.386] [64] -> 04-A0-02-BA-00-3A | 1E-00-50-44-50-2E-58-62-6F-78-2E-43-6F-6E-74-72-6F-6C-6C-65-72-2E-42-6F-6F-74-6C-6F-61-64-65-72-27-00-57-69-6E-64-6F-77-73-2E-58-62-6F-78-2E-49-6E-70-75-74-2E-4E-61-76-69-67
[2024-08-13 06:25:21.393] [64] -> 04-A0-02-BA-00-74 | 61-74-69-6F-6E-43-6F-6E-74-72-6F-6C-6C-65-72-03-DA-12-7C-06-CC-E0-7F-45-A1-E8-D8-B3-89-95-81-39-E7-1F-F3-B8-86-73-E9-40-A9-F8-2F-21-26-3A-CF-B7-56-FF-76-97-FD-9B-81-45-AD-45
[2024-08-13 06:25:21.397] [64] -> 04-A0-02-3A-AE-01 | B6-45-BB-A5-26-D6-07-17-00-20-3C-00-01-00-10-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-17-00-21-3C-00-01-00-10-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-17-00-30-3C-00
[2024-08-13 06:25:21.406] [64] -> 04-B0-02-3A-E8-01 | 01-00-18-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-17-00-31-3C-00-01-00-18-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-17-00-32-3C-00-01-00-18-00-00-00-00-00-00-00-00-00
[2024-08-13 06:25:21.425] [13] <- 01-20-02-09 | 00-04-20-22-01-00-00-34-00
[2024-08-13 06:25:21.430] [58] -> 04-B0-02-34-A2-02 | 00-00-00-00-00-00-17-00-33-3C-00-01-00-18-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-17-00-34-3C-00-01-00-18-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
[2024-08-13 06:25:21.439] [13] <- 01-20-02-09 | 00-04-20-56-01-00-00-00-00
[2024-08-13 06:25:21.445] [06] -> 04-A0-02-00-D6-02 | 
Could not find any supported interface IDs! Device will not be mapped.
Consider filing a GitHub issue with the GUIDs below if this device should be supported:
- 067c12da-e0cc-457f-a1e8-d8b389958139
- b8f31fe7-7386-40e9-a9f8-2f21263acfb7
- 9776ff56-9bfd-4581-ad45-b645bba526d6
[2024-08-13 06:25:21.460] [05] <- 05-20-01-01 | 00
[2024-08-13 06:25:21.461] [07] <- 0A-20-01-03 | 00-01-14
[2024-08-13 06:25:21.477] [06] <- 06-20-01-02 | 01-00
[2024-08-13 06:25:21.485] [08] -> 03-20-03-04 | 80-01-00-00
[2024-08-13 06:25:21.493] [08] -> 03-20-04-04 | 80-00-00-00
Rebooting USB devices to refresh them after mapping...
(If this takes more than 15 seconds or so, try re-connecting your devices.)
[2024-08-13 06:25:39.052] [05] <- 05-20-00-01 | 07
Error while reading packet! (Attempt 1)
Nefarius.Drivers.WinUSB.USBException: Failed to read from pipe. ---> Nefarius.Drivers.WinUSB.API.APIException: Failed to read pipe on WinUSB device. ---> System.ComponentModel.Win32Exception: The I/O operation has been aborted because of either a thread exit or an application request

[2024-08-13 06:25:41.485] [08] -> 03-20-05-04 | 80-00-00-00
USB device \\?\usb#vid_0e6f&pid_0247#0000db87a72a2019#{a5dcbf10-6530-11d2-901f-00c04fb951ed} disconnected
Stopped capture.
Packet logs may be found in C:\Users\Pellux\Documents\RB4InstrumentMapper\PacketLogs
GameInput device 12-98-7C-EF-0A-47-B8-F3-8C-FB-39-2F-6D-61-55-3D-C9-9A-EB-F0-8E-14-C3-0D-70-94-51-87-2F-BF-FD-03 disconnected
```

**Comment by TheNathannator** [comment]
> Should I be using the GameInput drivers or the WinUSB drivers?

WinUSB is the better one for this, as it provides more of the low-level data that I'd want.

I got the [connection data decoded](https://github.com/user-attachments/files/16605973/output.txt); unfortunately I don't think this mode does report any input data. One of the class name strings provided is `PDP.Xbox.Controller.Bootloader`, which tells me this is nothing more than a development/firmware update mode.

**Comment by pellux-network** [comment]
> > Should I be using the GameInput drivers or the WinUSB drivers?
> 
> WinUSB is the better one for this, as it provides more of the low-level data that I'd want. GameInput wouldn't have any more data than WinUSB already would.
> 
> I got the [connection data decoded](https://github.com/user-attachments/files/16605973/output.txt); unfortunately I don't think this mode does report any input data. One of the class name strings provided is `PDP.Xbox.Controller.Bootloader`, which tells me this is nothing more than a development/firmware update mode.

Dang, that's a bummer :/ At least we can confirm wired isn't supported for sure now! Thanks for checking this out :)

**Comment by TheNathannator** [comment]
Of course; it was definitely an interesting find!

It seems the Playstation version *does* function in this wired mode based on some other reports (for some reason it works as an XInput device lol), so the discovery wasn't *completely* fruitless at least.
