### ISSUE TITLE
Riffmaster causing program crashes

### ISSUE THREAD

**Issue by hifiTy** [TheNathannator/RB4InstrumentMapper#33]
I just got my Xbox Riffmaster today and cannot get through the process. I've downloaded version 5.0.4 ,vJoy, and ViGEmBus with no issues, but the RB4InstrumentMapper program crashes as soon as my Riffmaster connects to my PC. If the guitar is disconnected, the program seems to work just fine. I can't actually hit 'Start' since no controllers are connected, but I can see that both vJoy and ViGEmBus are showing as available in the console.

What's strange is that some troubleshooting posts recommended to use Zadig to update the guitar driver to WinUSB and restart my PC. At that point, the program would stay open with the guitar connected, but it crashed the moment I enabled the check box for WinUSB Backend and the device still wasn't registering in the console.

I tried downloading version 5.0.0 and that's the one that seemed to get me the furthest. It stays open with the guitar connected, the device is registering in the console, and the driver is showing up in the GameInput Xbox Controllers after clicking 'Configure USB Devices,' but the moment I hit 'Switch Driver' or 'Start' the program crashes. 

I don't have any packet or error logs because the program is crashing before I can even start it. This seems to be a brand new issue because I haven't seen anyone mention anything similar... I'm completely at a loss so any input would be much appreciated!

**Comment by hifiTy** [comment]
Quick update: I uninstalled everything and reverted the driver to factory by uninstalling in Device Manager. I ran Zadig again to update the driver to WinUSB, re-downloaded ViGEmBus and v5.0.4 and finally got the program to stay open with the guitar connected. The driver is showing as a WinUSB Xbox Controller as expected, but it still doesn't seem to be working in Clone Hero.

CH doesn't seem to be picking up any inputs even though it sees the device connected. Log file is attached.
[log_2024-08-14_22-44-35.txt](https://github.com/user-attachments/files/16621021/log_2024-08-14_22-44-35.txt)

**Comment by TheNathannator** [comment]
You don't need to use WinUSB anymore for a Riffmaster, I'd recommend sticking with the GameInput backend if possible. I'm not sure why it wouldn't be working in CH here though, there's nothing unusual in the log except for that one client ID of 0 (those two read exceptions are expected when stopping/disconnecting).

**Comment by hifiTy** [comment]
Thanks for responding so quickly. I reset the guitar drivers to factory again, restarted my PC, and everything worked perfectly through the GameInput backend. I have zero clue what was causing the issues before but it seems like uninstalling and re-installing everything fixed the problem. Wish I had more insight to offer anyone else who runs into the same issue.

**Comment by hifiTy** [comment]
Thanks for responding so quickly. I reset the guitar drivers to factory again, restarted my PC, and everything worked perfectly through the GameInput backend. I have zero clue what was causing the issues before but it seems like uninstalling and re-installing everything fixed the problem. Wish I had more insight to offer anyone else who runs into the same issue.

**Comment by TheNathannator** [comment]
Yeah, not much more I could suggest for that issue lol

If you want you could check in Event Viewer around the times of the crashes, but I'm not too fussed about it for now. It does just sound like something didn't install correctly, and so something slipped past error checks and made it crash.
