### ISSUE TITLE
RB4 drums via legacy adapter not working

### ISSUE THREAD

**Issue by masilu77** [TheNathannator/RB4InstrumentMapper#5]
First of all, thank you for the great work! 
I have installed the version 4.0.2.0 but the RB4 beatles drum via legacy adapter, still doesn't work.
It seems that the mapping between the drums pad/cymbal and the ViGEmBus virtual controller is not correct. 
When i press the start and back button they are correctly mapped to the button 7 and 8 of the virtual controller. The d-pad is correctly mappet to the virtual controller POV too. The pedal, cymbal, pad and a, x, y, b, button are not recognized or wrongly mapped-
ES: the yellow cymbal is mapped to the Z axis, the yellow and green pad are not recognized.

Note that with the RB4 Beatles guitar all is working properly

If you need other data/test i will be happy to help
Thank You

[log_2023-12-14_20-59-02.txt](https://github.com/TheNathannator/RB4InstrumentMapper/files/13677693/log_2023-12-14_20-59-02.txt)

**Comment by TheNathannator** [comment]
Okay yeah, there's probably more that I missed, another person on Discord reported the same issue. I'll take a closer look today, sounds like it's not detecting it as a drumkit for some reason.

**Comment by coopstev** [comment]
Unrelated: how can I join the Discord, @TheNathannator ?

**Comment by TheNathannator** [comment]
There isn't a server specific to this project, it was just in the [Clone Hero Discord](https://discord.gg/Hsn4Cgu).

**Comment by TheNathannator** [comment]
Alright, this issue should be fixed in [v4.0.3](https://github.com/TheNathannator/RB4InstrumentMapper/releases/tag/v4.0.3)! Let me know how things go.
