### ISSUE TITLE
Mouse drift from tilt and whammy bar

### ISSUE THREAD

**Issue by KingZarkon** [TheNathannator/RB4InstrumentMapper#6]
When the controller is connected and the program is running, the mouse cursor drifts. Tilting the guitar will control the Y-axis drift. The whammy bar seems to affect the X-axis but it's not really controllable. I've tried both ViGEmBus and vJoy and it does the same thing on both. Sometimes turning off the controller will fix it but often the drift continues and I have to kill RB44InstrumentMapper via the command prompt. 

Edit: I retract this. The issue appears to have possibly been Steam.

**Comment by TheNathannator** [comment]
Yeah, this is definitely a Steam issue. Its default desktop config maps the right stick of Xbox 360 gamepads to the mouse, which the guitar uses for tilt/whammy, and like most games it treats all Xbox 360 controllers as gamepads regardless of the actual type.

RB4InstrumentMapper doesn't do anything for mouse control anywhere, it's just ViGEmBus and vJoy. (Odd that it happens with vJoy though, Steam shouldn't be doing anything with generic controllers until you configure them.)
